[package]
name = "twisted_elgamal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curve25519-dalek = { version = "3", features = ["serde"] }
merlin = "2.0.0"
rand_core = { version = "0.5", default-features = false }
rand = "0.7"
